// <auto-generated />
using System;
using Cigirci.Budgeteer.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cigirci.Budgeteer.DbContext.Migrations
{
    [DbContext(typeof(BudgeteerContext))]
    partial class BudgeteerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Cigirci.Budgeteer.Models.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("company");
                });

            modelBuilder.Entity("Cigirci.Budgeteer.Models.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("amount");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("balance");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("goal");
                });

            modelBuilder.Entity("Cigirci.Budgeteer.Models.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("group");
                });

            modelBuilder.Entity("Cigirci.Budgeteer.Models.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ranking")
                        .HasColumnType("int")
                        .HasColumnName("rank");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("group_member");
                });

            modelBuilder.Entity("Cigirci.Budgeteer.Models.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("Account")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("balance");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<int?>("Sex")
                        .HasColumnType("int")
                        .HasColumnName("sex");

                    b.HasKey("Id");

                    b.ToTable("profile");
                });

            modelBuilder.Entity("Cigirci.Budgeteer.Models.Entities.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Currency")
                        .HasColumnType("int")
                        .HasColumnName("currency");

                    b.Property<int>("Language")
                        .HasColumnType("int")
                        .HasColumnName("language");

                    b.HasKey("Id");

                    b.ToTable("user_settings");
                });

            modelBuilder.Entity("Cigirci.Budgeteer.Models.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("Due")
                        .HasColumnType("datetime2")
                        .HasColumnName("due_date");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("Recurrence")
                        .HasColumnType("int")
                        .HasColumnName("recurrence");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.ToTable("subscription");
                });

            modelBuilder.Entity("Cigirci.Budgeteer.Models.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("transaction");
                });

            modelBuilder.Entity("Cigirci.Budgeteer.Models.Entities.Company", b =>
                {
                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Created", "Created", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("created_by");

                            b1.Property<DateTime>("On")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_on");

                            b1.HasKey("CompanyId");

                            b1.ToTable("company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Models.Components.Metadata.Modified", "Modified", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("modified_by");

                            b1.Property<DateTime>("On")
                                .HasColumnType("datetime2")
                                .HasColumnName("modified_on");

                            b1.HasKey("CompanyId");

                            b1.ToTable("company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Owner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("owner_id");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("owner_type");

                            b1.HasKey("CompanyId");

                            b1.ToTable("company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Status", "Status", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Reason")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("status");

                            b1.Property<int>("State")
                                .HasColumnType("int")
                                .HasColumnName("state");

                            b1.HasKey("CompanyId");

                            b1.ToTable("company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("Modified")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("Cigirci.Budgeteer.Models.Entities.Goal", b =>
                {
                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Created", "Created", b1 =>
                        {
                            b1.Property<Guid>("GoalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("created_by");

                            b1.Property<DateTime>("On")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_on");

                            b1.HasKey("GoalId");

                            b1.ToTable("goal");

                            b1.WithOwner()
                                .HasForeignKey("GoalId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Models.Components.Metadata.Modified", "Modified", b1 =>
                        {
                            b1.Property<Guid>("GoalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("modified_by");

                            b1.Property<DateTime>("On")
                                .HasColumnType("datetime2")
                                .HasColumnName("modified_on");

                            b1.HasKey("GoalId");

                            b1.ToTable("goal");

                            b1.WithOwner()
                                .HasForeignKey("GoalId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Owner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("GoalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("owner_id");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("owner_type");

                            b1.HasKey("GoalId");

                            b1.ToTable("goal");

                            b1.WithOwner()
                                .HasForeignKey("GoalId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Status", "Status", b1 =>
                        {
                            b1.Property<Guid>("GoalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Reason")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("status");

                            b1.Property<int>("State")
                                .HasColumnType("int")
                                .HasColumnName("state");

                            b1.HasKey("GoalId");

                            b1.ToTable("goal");

                            b1.WithOwner()
                                .HasForeignKey("GoalId");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("Modified")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("Cigirci.Budgeteer.Models.Entities.Group", b =>
                {
                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Created", "Created", b1 =>
                        {
                            b1.Property<Guid>("GroupId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("created_by");

                            b1.Property<DateTime>("On")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_on");

                            b1.HasKey("GroupId");

                            b1.ToTable("group");

                            b1.WithOwner()
                                .HasForeignKey("GroupId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Models.Components.Metadata.Modified", "Modified", b1 =>
                        {
                            b1.Property<Guid>("GroupId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("modified_by");

                            b1.Property<DateTime>("On")
                                .HasColumnType("datetime2")
                                .HasColumnName("modified_on");

                            b1.HasKey("GroupId");

                            b1.ToTable("group");

                            b1.WithOwner()
                                .HasForeignKey("GroupId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Owner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("GroupId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("owner_id");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("owner_type");

                            b1.HasKey("GroupId");

                            b1.ToTable("group");

                            b1.WithOwner()
                                .HasForeignKey("GroupId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Status", "Status", b1 =>
                        {
                            b1.Property<Guid>("GroupId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Reason")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("status");

                            b1.Property<int>("State")
                                .HasColumnType("int")
                                .HasColumnName("state");

                            b1.HasKey("GroupId");

                            b1.ToTable("group");

                            b1.WithOwner()
                                .HasForeignKey("GroupId");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("Modified")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("Cigirci.Budgeteer.Models.Entities.Member", b =>
                {
                    b.HasOne("Cigirci.Budgeteer.Models.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Created", "Created", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("created_by");

                            b1.Property<DateTime>("On")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_on");

                            b1.HasKey("MemberId");

                            b1.ToTable("group_member");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Models.Components.Metadata.Modified", "Modified", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("modified_by");

                            b1.Property<DateTime>("On")
                                .HasColumnType("datetime2")
                                .HasColumnName("modified_on");

                            b1.HasKey("MemberId");

                            b1.ToTable("group_member");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Owner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("owner_id");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("owner_type");

                            b1.HasKey("MemberId");

                            b1.ToTable("group_member");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Status", "Status", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Reason")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("status");

                            b1.Property<int>("State")
                                .HasColumnType("int")
                                .HasColumnName("state");

                            b1.HasKey("MemberId");

                            b1.ToTable("group_member");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Modified")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("Cigirci.Budgeteer.Models.Entities.Profile", b =>
                {
                    b.OwnsOne("Cigirci.Budgeteer.Models.Components.Profile.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("First")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("first_name");

                            b1.Property<string>("Last")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("last_name");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profile");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Created", "Created", b1 =>
                        {
                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("created_by");

                            b1.Property<DateTime>("On")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_on");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profile");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Models.Components.Metadata.Modified", "Modified", b1 =>
                        {
                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("modified_by");

                            b1.Property<DateTime>("On")
                                .HasColumnType("datetime2")
                                .HasColumnName("modified_on");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profile");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Owner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("owner_id");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("owner_type");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profile");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Status", "Status", b1 =>
                        {
                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Reason")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("status");

                            b1.Property<int>("State")
                                .HasColumnType("int")
                                .HasColumnName("state");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profile");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("Modified")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("Cigirci.Budgeteer.Models.Entities.Settings", b =>
                {
                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Created", "Created", b1 =>
                        {
                            b1.Property<Guid>("SettingsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("created_by");

                            b1.Property<DateTime>("On")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_on");

                            b1.HasKey("SettingsId");

                            b1.ToTable("user_settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingsId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Models.Components.Metadata.Modified", "Modified", b1 =>
                        {
                            b1.Property<Guid>("SettingsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("modified_by");

                            b1.Property<DateTime>("On")
                                .HasColumnType("datetime2")
                                .HasColumnName("modified_on");

                            b1.HasKey("SettingsId");

                            b1.ToTable("user_settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingsId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Owner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("SettingsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("owner_id");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("owner_type");

                            b1.HasKey("SettingsId");

                            b1.ToTable("user_settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingsId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Status", "Status", b1 =>
                        {
                            b1.Property<Guid>("SettingsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Reason")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("status");

                            b1.Property<int>("State")
                                .HasColumnType("int")
                                .HasColumnName("state");

                            b1.HasKey("SettingsId");

                            b1.ToTable("user_settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingsId");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("Modified")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("Cigirci.Budgeteer.Models.Entities.Subscription", b =>
                {
                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Created", "Created", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("created_by");

                            b1.Property<DateTime>("On")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_on");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("subscription");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Models.Components.Metadata.Modified", "Modified", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("modified_by");

                            b1.Property<DateTime>("On")
                                .HasColumnType("datetime2")
                                .HasColumnName("modified_on");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("subscription");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Owner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("owner_id");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("owner_type");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("subscription");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Status", "Status", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Reason")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("status");

                            b1.Property<int>("State")
                                .HasColumnType("int")
                                .HasColumnName("state");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("subscription");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("Modified")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("Cigirci.Budgeteer.Models.Entities.Transaction", b =>
                {
                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Created", "Created", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("created_by");

                            b1.Property<DateTime>("On")
                                .HasColumnType("datetime2")
                                .HasColumnName("created_on");

                            b1.HasKey("TransactionId");

                            b1.ToTable("transaction");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Models.Components.Metadata.Modified", "Modified", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("By")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("modified_by");

                            b1.Property<DateTime>("On")
                                .HasColumnType("datetime2")
                                .HasColumnName("modified_on");

                            b1.HasKey("TransactionId");

                            b1.ToTable("transaction");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Owner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("owner_id");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("owner_type");

                            b1.HasKey("TransactionId");

                            b1.ToTable("transaction");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("Cigirci.Budgeteer.Interfaces.Metadata.Record.Types.Status", "Status", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Reason")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("status");

                            b1.Property<int>("State")
                                .HasColumnType("int")
                                .HasColumnName("state");

                            b1.HasKey("TransactionId");

                            b1.ToTable("transaction");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("Modified")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
